
ver: 1.0

file:
    path: '/Users/dgursoy/Data/Dina/Si10Norcada90_wireHstep'
    output: 'tmp/recon-Si10Norcada90_wireHstep'
    range: [0, 401, 1]
    threshold: 0 # [readout values]
    frame: [0, 2048, 0, 2048] # [pixels] 
    ext: 'h5'
    stacked: False
    h5:
        key: '/entry1/data/data'

comp:
    server: 'acc'
    workers: 1
    scanstart: 1
    batch_size_cpu: 8
    batch_size_gpu: 3000
    scannumber: 1
    functionid: 'd8461388-9442-4008-a5f1-2cfa112f6923'

geo:
    mask: 
        path: '/home/aps34ide/laue_src/laue-parallel/masks/code-debruijn-2-8-000.npy'
        reversed: False
        bitsizes: [15, 7.5] # [mu]
        thickness: 3.73901367 # [mu]
        resolution: 0.5
        smoothness: 0 # [mu]
        alpha: 0
        widening: 0 # [mu]
        pad: 150
        stretch: 1.0

        focus:
            cenx: 0.525634766
            dist: 1.90576172
            anglez: 44.2087891
            angley: -0.0683593750
            anglex: -0.0136718750
            cenz: -0.623046875
            cons: 100.0

        calibrate: 
            dist: [1.5, 3.0, 0.1] # [mm] 0.619

    scanner:
        step: 1 # [mu]
        rot: [0.0045, -0.00684, -3.375e-5]
        axis: [0.70710678118, 0.70710678118, 0]

    detector: 
        shape: [2048, 2048] # [pixels]
        size: [409.6, 409.6] # [mm]
        rot: [-1.20100922, -1.21370698, -1.21901611] # [radian]
        pos: [28.611, 2.714, 513.155] # [mm]

    source: 
        offset: 0
        grid:  [-0.3, 0.3, 0.001]  # [mm]

algo:
    iter: 1
    pos: 
        method: 'lsqr' 
        regpar: 0
        init: 'spline'

    sig: 
        method: 'splines' 
        order: 1
        scale: 1
        init:
            maxsize: 64 
            avgsize: 10
            atol: 4


