import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/navbar'
import Sidebar from './components/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Laue Portal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <div>
          <div className="drawer drawer-open flex-col h-full w-full overflow-hidden">
            <input id="my-drawer" type="checkbox" className="drawer-toggle" /> {/* Invisible control button */}
            <div className="drawer-content bg-base-200">
              <Navbar />
              <div className="p-5 mt-1 flex-1 overflow-auto h-0 min-h-[90%] w-0 min-w-[100%]">
                {children}
              </div>
            </div>
            <Sidebar />
          </div>
        </div>
      </body>
    </html>
  )
}
