import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/navbar'
import Sidebar from './containers/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Laue Portal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <Navbar />
        <div className="drawer drawer-open">
          <input id="my-drawer" type="checkbox" className="drawer-toggle" /> {/* Invisible control button */}
          <div className="drawer-content flex flex-col bg-base-200">
            <div className="p-5">
              <div className="card bg-base-100 shadow-xl">
                <div className="card-body">
                  {children}
                </div>
              </div>
            </div>
          </div>
          <Sidebar />
        </div>
      </body>
    </html>
  )
}
